extends Node
## Persists all player data to user://save.json.

const SAVE_PATH := "user://save.json"
const BACKUP_PATH := "user://save.json.bak"
const DISCOVERY_KEYS: Array[String] = [
	"DISCOVERY_FULL_CITY", "DISCOVERY_MWENGE", "DISCOVERY_MASTERY",
	"DISCOVERY_WEATHER", "DISCOVERY_GHOST", "DISCOVERY_POLICE",
]

var data: Dictionary = {}
var _batch_depth: int = 0
var _batch_dirty: bool = false

const DEFAULTS := {
	"schema_version": 14,
	"best_score": 0,
	"best_reputation": 0,
	"total_coins": 0,
	"selected_vehicle": "classic_blue",
	"selected_route": "kariakoo",
	"unlocked_vehicles": ["classic_blue"],
	"unlocked_routes": ["kariakoo"],
	"music_on": true,
	"sfx_on": true,
	"haptics_on": true,
	"reduced_effects": false,
	"locale": "sw",
	# Career stats
	"total_runs": 0,
	"regular_runs": 0,
	"total_distance_ever": 0.0,
	"total_coins_ever": 0,
	"total_passengers_ever": 0,
	# Route personal bests
	"best_kariakoo": 0,
	"best_mwenge": 0,
	"best_mbezi": 0,
	"best_posta": 0,
	"best_kigamboni": 0,
	"best_ubungo": 0,
	# Achievements (array of unlocked id strings)
	"achievements": [],
	"route_goals_completed": 0,
	# Route id -> permanent 0-3 mastery stars.
	"route_mastery": {},
	# Route id -> local date. One short route contract can pay per route/day.
	"route_contract_claimed_on": {},
	"daily_challenge_claimed_date": "",
	"daily_challenges_completed": 0,
	# Ad pacing. Keep this local so interstitial cadence survives restarts.
	"ads_runs_since_interstitial": 0,
	"ads_next_interstitial_at": 2,
	"ads_pending_interstitial": false,
	# Daily login streak
	"streak_count": 0,
	"streak_last_date": "",
	# Consumable inventory: {item_id: count}
	"consumables": {},
	# Top-5 personal leaderboard: Array of {name, score, route}. The public
	# name is only sent after a separate online-leaderboard opt-in.
	"leaderboard": [],
	"leaderboard_display_name": "Dereva",
	"online_leaderboard_opt_in": false,
	"leaderboard_upload_status": "",
	"leaderboard_upload_route": "",
	"leaderboard_upload_score": 0,
	"leaderboard_upload_updated_at": 0,
	# Queued best scores survive an interrupted network request. Entries are
	# route-local and contain no player-entered text; the public name is read at
	# submit time after the player has explicitly opted in.
	"pending_leaderboard_submissions": [],
	"leaderboard_cache": {},
	"online_telemetry_opt_in": false,
	# Offline referral handshake. Codes are random game identifiers, not PII.
	"referral_invite_code": "",
	"referral_welcome_claimed": false,
	"referral_inviter_code": "",
	"referral_confirmation_code": "",
	"referral_claimed_invitees": [],
	"referral_success_count": 0,
	# First-session progression. 0 means no guided run has been completed yet.
	# Existing installs are treated as experienced by GameState, so this never
	# interrupts a player who upgrades from an earlier build.
	"first_session_stage": 0,
	# Feature discoveries are shown once, then retained locally so the first
	# session can introduce one useful system at a time.
	"seen_discoveries": [],
	# Offline analytics lifecycle markers. These are aggregate timestamps/counts,
	# never player-entered text, advertising identifiers, or contact data.
	"analytics_first_open_unix": 0,
	"analytics_last_open_unix": 0,
	"analytics_session_count": 0,
	# Optional Railway cloud-sync identity. The token is generated by the
	# backend after an explicit opt-in; the game remains fully offline without it.
	"online_installation_id": "",
	"online_sync_token": "",
	"online_cloud_revision": 0,
	"cloud_sync_opt_in": false,
}

func _ready() -> void:
	load_data()

func load_data() -> void:
	data = DEFAULTS.duplicate(true)
	# Try the main save, fall back to the backup if missing/corrupt.
	if not _load_from(SAVE_PATH):
		if _load_from(BACKUP_PATH):
			push_warning("Save: main file corrupt or missing — restored from backup.")
			# Restore the primary immediately without rotating the corrupt file over
			# the known-good backup. The next ordinary save may rotate normally.
			if not save(false):
				push_warning("Save: backup loaded, but the primary could not be restored.")

func _load_from(path: String) -> bool:
	if not FileAccess.file_exists(path):
		return false
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		return false
	var text := f.get_as_text()
	f.close()
	var parsed: Variant = JSON.parse_string(text)
	if typeof(parsed) != TYPE_DICTIONARY:
		return false
	for k in parsed.keys():
		var key := String(k)
		var value: Variant = parsed[k]
		if DEFAULTS.has(key) and not _is_compatible_value(DEFAULTS[key], value):
			push_warning("Save: ignored invalid value for '%s'." % key)
			continue
		data[key] = value
	if not parsed.has("regular_runs"):
		data["regular_runs"] = int(data.get("total_runs", 0))
	_normalize_core_data()
	return true

func _is_compatible_value(default_value: Variant, loaded_value: Variant) -> bool:
	var expected_type := typeof(default_value)
	var loaded_type := typeof(loaded_value)
	if expected_type in [TYPE_INT, TYPE_FLOAT] and loaded_type in [TYPE_INT, TYPE_FLOAT]:
		return true
	return expected_type == loaded_type

func _normalize_core_data() -> void:
	if not data.has("regular_runs"):
		data["regular_runs"] = int(data.get("total_runs", 0))
	data["schema_version"] = int(DEFAULTS["schema_version"])
	var non_negative_ints: Array[String] = [
		"best_score", "best_reputation", "total_coins", "total_runs", "regular_runs", "total_coins_ever",
		"total_passengers_ever", "route_goals_completed",
		"daily_challenges_completed", "ads_runs_since_interstitial",
		"ads_next_interstitial_at", "streak_count",
		"referral_success_count", "first_session_stage", "analytics_first_open_unix",
		"analytics_last_open_unix", "analytics_session_count",
		"online_cloud_revision", "leaderboard_upload_score", "leaderboard_upload_updated_at",
		"best_kariakoo", "best_mwenge", "best_mbezi", "best_posta",
		"best_kigamboni", "best_ubungo",
	]
	for key in non_negative_ints:
		data[key] = maxi(0, int(data.get(key, DEFAULTS.get(key, 0))))
	data["total_distance_ever"] = maxf(0.0, float(data.get("total_distance_ever", 0.0)))
	_normalize_online_identity()
	data["leaderboard_display_name"] = normalize_leaderboard_name(
		String(data.get("leaderboard_display_name", "Dereva"))
	)
	data["online_leaderboard_opt_in"] = bool(data.get("online_leaderboard_opt_in", false))
	data["online_telemetry_opt_in"] = bool(data.get("online_telemetry_opt_in", false))
	var upload_status: String = String(data.get("leaderboard_upload_status", ""))
	data["leaderboard_upload_status"] = upload_status if upload_status in [
		"pending", "retry", "rate_limited", "invalid_name", "submitted", "superseded",
	] else ""
	var upload_route: String = String(data.get("leaderboard_upload_route", ""))
	data["leaderboard_upload_route"] = upload_route if _is_known_route_id(upload_route) else ""

	data["unlocked_vehicles"] = _normalized_string_array(
		data.get("unlocked_vehicles", []), "classic_blue"
	)
	data["unlocked_routes"] = _normalized_string_array(
		data.get("unlocked_routes", []), "kariakoo"
	)
	data["achievements"] = _normalized_string_array(data.get("achievements", []))
	data["referral_claimed_invitees"] = _normalized_string_array(
		data.get("referral_claimed_invitees", [])
	)
	data["referral_success_count"] = (data["referral_claimed_invitees"] as Array).size()
	data["first_session_stage"] = clampi(int(data.get("first_session_stage", 0)), 0, 3)
	_normalize_seen_discoveries()

	var locale := String(data.get("locale", "sw"))
	data["locale"] = locale if locale in ["sw", "en"] else "sw"
	_normalize_consumables()
	_normalize_leaderboard()
	_normalize_pending_leaderboard_submissions()
	_normalize_leaderboard_cache()
	_normalize_route_mastery()
	_normalize_route_contract_claims()

func _normalized_string_array(value: Variant, required_value: String = "") -> Array[String]:
	var result: Array[String] = []
	if value is Array:
		for item in value:
			if typeof(item) != TYPE_STRING:
				continue
			var text := String(item).strip_edges()
			if not text.is_empty() and text not in result:
				result.append(text)
	if not required_value.is_empty() and required_value not in result:
		result.push_front(required_value)
	return result

func _normalize_seen_discoveries() -> void:
	var clean: Array[String] = []
	for key in _normalized_string_array(data.get("seen_discoveries", [])):
		if key in DISCOVERY_KEYS:
			clean.append(key)
	data["seen_discoveries"] = clean

func _normalize_consumables() -> void:
	var clean: Dictionary = {}
	var source: Dictionary = data.get("consumables", {})
	for raw_id in source.keys():
		var item_id := String(raw_id).strip_edges()
		var count_value: Variant = source[raw_id]
		if typeof(count_value) not in [TYPE_INT, TYPE_FLOAT]:
			continue
		var count := maxi(0, int(count_value))
		if not item_id.is_empty() and count > 0:
			clean[item_id] = count
	data["consumables"] = clean

func _normalize_leaderboard() -> void:
	var clean: Array[Dictionary] = []
	var source: Array = data.get("leaderboard", [])
	for value in source:
		if not value is Dictionary:
			continue
		var row: Dictionary = value
		var score_value: Variant = row.get("score", 0)
		if typeof(score_value) not in [TYPE_INT, TYPE_FLOAT]:
			continue
		var score := maxi(0, int(score_value))
		if score <= 0:
			continue
		var name_value: Variant = row.get("name", "Dereva")
		var player_name := "Dereva"
		if typeof(name_value) == TYPE_STRING:
			player_name = normalize_leaderboard_name(String(name_value))
		var route_value: Variant = row.get("route", "kariakoo")
		var route_id := String(route_value) if typeof(route_value) == TYPE_STRING else "kariakoo"
		clean.append({
			"name": player_name,
			"score": score,
			"route": route_id,
		})
	clean.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return int(a.score) > int(b.score))
	if clean.size() > 5:
		clean.resize(5)
	data["leaderboard"] = clean

func _normalize_pending_leaderboard_submissions() -> void:
	var best_by_route: Dictionary = {}
	var source: Variant = data.get("pending_leaderboard_submissions", [])
	if source is Array:
		for value in source:
			if value is not Dictionary:
				continue
			var row: Dictionary = value
			var route_id: String = String(row.get("route", "")).strip_edges().to_lower()
			var score: int = maxi(0, int(row.get("score", 0)))
			if not _is_known_route_id(route_id) or score <= 0:
				continue
			var previous: int = int(best_by_route.get(route_id, 0))
			if score > previous:
				best_by_route[route_id] = score
	var clean: Array[Dictionary] = []
	for route_id_value in best_by_route.keys():
		clean.append({"route": String(route_id_value), "score": int(best_by_route[route_id_value])})
	clean.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return int(a.score) > int(b.score))
	data["pending_leaderboard_submissions"] = clean.slice(0, 6)

func _normalize_leaderboard_cache() -> void:
	var clean: Dictionary = {}
	var source: Variant = data.get("leaderboard_cache", {})
	if source is Dictionary:
		for raw_key in source.keys():
			var key: String = String(raw_key)
			var entry: Variant = source[raw_key]
			if not key.contains(":") or entry is not Dictionary:
				continue
			var cache: Dictionary = entry
			var fetched_at: int = maxi(0, int(cache.get("fetched_at", 0)))
			var raw_scores: Variant = cache.get("scores", [])
			if fetched_at <= 0 or raw_scores is not Array:
				continue
			clean[key] = {"fetched_at": fetched_at, "scores": (raw_scores as Array).slice(0, 25)}
	data["leaderboard_cache"] = clean

func _is_known_route_id(route_id: String) -> bool:
	return route_id in ["kariakoo", "mwenge", "mbezi", "posta", "kigamboni", "ubungo"]

func _normalize_route_mastery() -> void:
	var clean: Dictionary = {}
	var source: Variant = data.get("route_mastery", {})
	if source is Dictionary:
		for raw_route_id in source.keys():
			var route_id: String = String(raw_route_id).strip_edges()
			var stars_value: Variant = source[raw_route_id]
			if route_id.is_empty() or typeof(stars_value) not in [TYPE_INT, TYPE_FLOAT]:
				continue
			var stars: int = clampi(int(stars_value), 0, 3)
			if stars > 0:
				clean[route_id] = stars
	data["route_mastery"] = clean

func _normalize_route_contract_claims() -> void:
	var clean: Dictionary = {}
	var source: Variant = data.get("route_contract_claimed_on", {})
	if source is Dictionary:
		for raw_route_id in source.keys():
			var route_id: String = String(raw_route_id).strip_edges().to_lower()
			var date_value: Variant = source[raw_route_id]
			if route_id.is_empty() or route_id.length() > 32 or typeof(date_value) != TYPE_STRING:
				continue
			var date_key: String = String(date_value)
			var parts: PackedStringArray = date_key.split("-")
			if parts.size() == 3 and parts[0].length() == 4 and parts[1].length() == 2 and parts[2].length() == 2:
				clean[route_id] = date_key
	data["route_contract_claimed_on"] = clean

func _normalize_online_identity() -> void:
	var installation_id: Variant = data.get("online_installation_id", "")
	var sync_token: Variant = data.get("online_sync_token", "")
	data["online_installation_id"] = String(installation_id).strip_edges() \
		if typeof(installation_id) == TYPE_STRING and String(installation_id).length() <= 64 else ""
	data["online_sync_token"] = String(sync_token).strip_edges() \
		if typeof(sync_token) == TYPE_STRING and String(sync_token).length() <= 128 else ""

func save(rotate_backup: bool = true) -> bool:
	# Rotate the last good save to .bak before overwriting,
	# so a crash mid-write can never lose everything.
	if rotate_backup and FileAccess.file_exists(SAVE_PATH):
		DirAccess.copy_absolute(SAVE_PATH, BACKUP_PATH)
	var f := FileAccess.open(SAVE_PATH, FileAccess.WRITE)
	if f == null:
		push_warning("Save: cannot open file for writing.")
		return false
	f.store_string(JSON.stringify(data))
	f.close()
	_batch_dirty = false
	return true

## Defers disk writes until the matching end_batch(). Calls may be nested.
func begin_batch() -> void:
	_batch_depth += 1

## Flushes all mutations once the outermost batch finishes.
func end_batch() -> void:
	if _batch_depth <= 0:
		push_warning("Save: end_batch called without begin_batch.")
		return
	_batch_depth -= 1
	if _batch_depth == 0 and _batch_dirty:
		save()

func _request_save() -> void:
	if _batch_depth > 0:
		_batch_dirty = true
	else:
		save()

func get_value(key: String, fallback: Variant = null) -> Variant:
	return data.get(key, fallback)

func set_value(key: String, value: Variant) -> void:
	data[key] = value
	_request_save()

# ── Coins ────────────────────────────────────────────────────────

func add_coins(amount: int) -> void:
	if amount <= 0:
		return
	data["total_coins"] = int(data.get("total_coins", 0)) + amount
	_request_save()

func spend_coins(amount: int) -> bool:
	var total := int(data.get("total_coins", 0))
	if amount < 0 or total < amount:
		return false
	data["total_coins"] = total - amount
	_request_save()
	return true

# ── Vehicles ─────────────────────────────────────────────────────

func unlock_vehicle(id: String) -> void:
	if id.is_empty():
		return
	var u: Array = data.get("unlocked_vehicles", [])
	if id not in u:
		u.append(id)
		data["unlocked_vehicles"] = u
		_request_save()

func is_vehicle_unlocked(id: String) -> bool:
	return id in data.get("unlocked_vehicles", [])

# ── First-session discoveries ────────────────────────────────────

func has_seen_discovery(key: String) -> bool:
	return key in data.get("seen_discoveries", [])

## Returns true only when this is the first time the discovery is recorded.
func mark_discovery_seen(key: String) -> bool:
	if key not in DISCOVERY_KEYS or has_seen_discovery(key):
		return false
	var seen: Array = data.get("seen_discoveries", [])
	seen.append(key)
	data["seen_discoveries"] = seen
	_request_save()
	return true

# ── Consumables ──────────────────────────────────────────────────

func get_consumable_count(id: String) -> int:
	var inv: Dictionary = data.get("consumables", {})
	return int(inv.get(id, 0))

func add_consumable(id: String, amount: int = 1) -> void:
	if id.is_empty() or amount <= 0:
		return
	var inv: Dictionary = data.get("consumables", {})
	inv[id] = int(inv.get(id, 0)) + amount
	data["consumables"] = inv
	_request_save()

## Returns true and decrements if at least one is owned.
func use_consumable(id: String) -> bool:
	var inv: Dictionary = data.get("consumables", {})
	var n := int(inv.get(id, 0))
	if n <= 0:
		return false
	inv[id] = n - 1
	data["consumables"] = inv
	_request_save()
	return true

# ── Routes ───────────────────────────────────────────────────────

func unlock_route(id: String) -> void:
	if id.is_empty():
		return
	var u: Array = data.get("unlocked_routes", [])
	if id not in u:
		u.append(id)
		data["unlocked_routes"] = u
		_request_save()

func is_route_unlocked(id: String) -> bool:
	return id in data.get("unlocked_routes", [])

# ── Scores ───────────────────────────────────────────────────────

func update_best_score(score: int) -> bool:
	if score > int(data.get("best_score", 0)):
		data["best_score"] = score
		_request_save()
		return true
	return false

func update_best_reputation(reputation: int) -> bool:
	var value: int = clampi(reputation, 0, 100)
	if value > int(data.get("best_reputation", 0)):
		data["best_reputation"] = value
		_request_save()
		return true
	return false

func update_route_best(route_id: String, score: int) -> bool:
	var key := "best_" + route_id
	if score > int(data.get(key, 0)):
		data[key] = score
		_request_save()
		return true
	return false

func get_route_best(route_id: String) -> int:
	return int(data.get("best_" + route_id, 0))

func get_route_mastery(route_id: String) -> int:
	var all_mastery: Dictionary = data.get("route_mastery", {})
	return clampi(int(all_mastery.get(route_id, 0)), 0, 3)

## Returns the number of newly earned stars. Rewards are calculated by
## GameState, which keeps the catalog/economy data out of the save layer.
func update_route_mastery(route_id: String, stars: int) -> int:
	if route_id.is_empty():
		return 0
	var previous: int = get_route_mastery(route_id)
	var attained: int = clampi(stars, 0, 3)
	if attained <= previous:
		return 0
	var all_mastery: Dictionary = data.get("route_mastery", {})
	all_mastery[route_id] = attained
	data["route_mastery"] = all_mastery
	_request_save()
	return attained - previous

# ── Career stats ─────────────────────────────────────────────────

func add_run_stats(distance: float, coins: int, passengers: int, count_run: bool = true,
		daily_run: bool = false) -> void:
	if count_run:
		data["total_runs"]      = int(data.get("total_runs", 0)) + 1
		if not daily_run:
			data["regular_runs"] = int(data.get("regular_runs", 0)) + 1
	data["total_distance_ever"] = float(data.get("total_distance_ever", 0.0)) + distance
	data["total_coins_ever"]    = int(data.get("total_coins_ever", 0)) + coins
	data["total_passengers_ever"] = int(data.get("total_passengers_ever", 0)) + passengers
	_request_save()

func add_route_goal_completion(route_id: String) -> void:
	data["route_goals_completed"] = int(data.get("route_goals_completed", 0)) + 1
	var key := "route_goal_" + route_id
	data[key] = int(data.get(key, 0)) + 1
	_request_save()

# ── Leaderboard ──────────────────────────────────────────────────

func qualifies_for_leaderboard(score: int) -> bool:
	var lb: Array = data.get("leaderboard", [])
	if lb.size() < 5:
		return score > 0
	return score > int(lb[lb.size() - 1].get("score", 0))

func add_to_leaderboard(player_name: String, score: int, route_id: String) -> void:
	var lb: Array = data.get("leaderboard", [])
	lb.append({"name": normalize_leaderboard_name(player_name), "score": score, "route": route_id})
	lb.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return int(a.score) > int(b.score))
	if lb.size() > 5:
		lb.resize(5)
	data["leaderboard"] = lb
	_request_save()

func get_leaderboard() -> Array:
	return data.get("leaderboard", [])

func get_personal_route_scores(route_id: String) -> Array:
	if not _is_known_route_id(route_id):
		return []
	var scores: Array = []
	var best_score: int = get_route_best(route_id)
	var includes_best: bool = false
	for row_value in get_leaderboard():
		if row_value is not Dictionary:
			continue
		var row: Dictionary = row_value
		if String(row.get("route", "")) != route_id:
			continue
		scores.append(row.duplicate(true))
		includes_best = includes_best or int(row.get("score", 0)) == best_score
	if best_score > 0 and not includes_best:
		scores.append({
			"name": get_leaderboard_display_name(),
			"score": best_score,
			"route": route_id,
		})
	scores.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return int(a.score) > int(b.score))
	return scores

func clear_online_account() -> void:
	for key in [
		"online_installation_id", "online_sync_token", "online_cloud_revision",
		"cloud_sync_opt_in", "online_leaderboard_opt_in", "online_telemetry_opt_in",
		"pending_leaderboard_submissions", "leaderboard_cache",
		"leaderboard_upload_status", "leaderboard_upload_route",
		"leaderboard_upload_score", "leaderboard_upload_updated_at",
	]:
		var default_value: Variant = DEFAULTS[key]
		data[key] = default_value.duplicate(true) if default_value is Array or default_value is Dictionary else default_value
	_request_save()

func is_route_personal_best(route_id: String, score: int) -> bool:
	return _is_known_route_id(route_id) and score > 0 and score >= get_route_best(route_id)

func queue_leaderboard_submission(route_id: String, score: int) -> bool:
	if not _is_known_route_id(route_id) or score <= 0:
		return false
	var queued: Array = data.get("pending_leaderboard_submissions", [])
	var found: bool = false
	for index in range(queued.size()):
		var entry: Variant = queued[index]
		if entry is Dictionary and String((entry as Dictionary).get("route", "")) == route_id:
			var next_score: int = maxi(score, int((entry as Dictionary).get("score", 0)))
			queued[index] = {"route": route_id, "score": next_score}
			found = true
			break
	if not found:
		queued.append({"route": route_id, "score": score})
	data["pending_leaderboard_submissions"] = queued
	_normalize_pending_leaderboard_submissions()
	set_leaderboard_upload_status("pending", route_id, score, false)
	_request_save()
	return true

func get_pending_leaderboard_submissions() -> Array:
	return (data.get("pending_leaderboard_submissions", []) as Array).duplicate(true)

func clear_submitted_leaderboard_score(route_id: String, submitted_score: int, accepted: bool = true) -> void:
	var queued: Array = data.get("pending_leaderboard_submissions", [])
	var keep: Array = []
	for entry in queued:
		if entry is Dictionary and String((entry as Dictionary).get("route", "")) == route_id \
				and int((entry as Dictionary).get("score", 0)) <= submitted_score:
			continue
		keep.append(entry)
	data["pending_leaderboard_submissions"] = keep
	set_leaderboard_upload_status("submitted" if accepted else "superseded", route_id, submitted_score, false)
	_request_save()

func set_leaderboard_upload_status(status: String, route_id: String = "", score: int = 0,
		persist: bool = true) -> void:
	if status not in ["", "pending", "retry", "rate_limited", "invalid_name", "submitted", "superseded"]:
		return
	data["leaderboard_upload_status"] = status
	data["leaderboard_upload_route"] = route_id if _is_known_route_id(route_id) else ""
	data["leaderboard_upload_score"] = maxi(0, score)
	data["leaderboard_upload_updated_at"] = int(Time.get_unix_time_from_system()) if not status.is_empty() else 0
	if persist:
		_request_save()

func get_leaderboard_upload_state() -> Dictionary:
	return {
		"status": String(data.get("leaderboard_upload_status", "")),
		"route": String(data.get("leaderboard_upload_route", "")),
		"score": maxi(0, int(data.get("leaderboard_upload_score", 0))),
		"updated_at": maxi(0, int(data.get("leaderboard_upload_updated_at", 0))),
	}

func cache_online_leaderboard(tab_id: String, route_id: String, scores: Array) -> void:
	if tab_id not in ["friends", "world"] or not _is_known_route_id(route_id):
		return
	var cache: Dictionary = data.get("leaderboard_cache", {})
	cache[tab_id + ":" + route_id] = {
		"fetched_at": int(Time.get_unix_time_from_system()),
		"scores": scores.slice(0, 25),
	}
	data["leaderboard_cache"] = cache
	_request_save()

func get_cached_online_leaderboard(tab_id: String, route_id: String) -> Dictionary:
	var cache: Dictionary = data.get("leaderboard_cache", {})
	var value: Variant = cache.get(tab_id + ":" + route_id, {})
	return (value as Dictionary).duplicate(true) if value is Dictionary else {}

func get_leaderboard_display_name() -> String:
	return normalize_leaderboard_name(String(data.get("leaderboard_display_name", "Dereva")))

func set_leaderboard_display_name(raw_name: String) -> String:
	var normalized := normalize_leaderboard_name(raw_name)
	data["leaderboard_display_name"] = normalized
	_request_save()
	return normalized

## Names are public only after a deliberate online-leaderboard opt-in. Keep the
## same conservative format on device and server: readable, no control chars,
## and short enough for narrow Android leaderboard rows.
static func normalize_leaderboard_name(raw_name: String) -> String:
	var cleaned := raw_name.strip_edges().replace("\n", " ").replace("\r", " ")
	var output := ""
	for index in range(cleaned.length()):
		var character := cleaned.substr(index, 1)
		var codepoint: int = character.unicode_at(0)
		var is_letter: bool = character.to_upper() != character.to_lower()
		var is_ascii_digit: bool = codepoint >= 48 and codepoint <= 57
		var is_separator: bool = character == " " or character == "." or character == "_" or character == "-"
		if not (is_letter or is_ascii_digit or is_separator):
			continue
		if output.is_empty() and is_separator:
			continue
		if character == " " and output.ends_with(" "):
			continue
		output += character
		if output.length() >= 16:
			break
	output = output.strip_edges()
	if output.length() < 2:
		return "Dereva"
	return output

static func is_reserved_leaderboard_name(raw_name: String) -> bool:
	var normalized: String = raw_name.strip_edges().to_lower()
	for separator in [".", "_", "-"]:
		normalized = normalized.replace(separator, " ")
	var reserved: Array[String] = [
		"admin", "administrator", "developer", "moderator", "official", "owner", "staff", "support", "system",
	]
	for part in normalized.split(" ", false):
		if String(part) in reserved:
			return true
	return false

func is_online_leaderboard_opted_in() -> bool:
	return bool(data.get("online_leaderboard_opt_in", false))

func set_online_leaderboard_opt_in(enabled: bool) -> void:
	data["online_leaderboard_opt_in"] = enabled
	_request_save()

func is_online_telemetry_opted_in() -> bool:
	return bool(data.get("online_telemetry_opt_in", false))

func set_online_telemetry_opt_in(enabled: bool) -> void:
	data["online_telemetry_opt_in"] = enabled
	_request_save()
